### ISSUE TITLE
FTO global fee is calculated incorrectly for turnover of 1.5 million

### ISSUE THREAD

**Issue by bbsen** [bmango/wfto_fees_calculator#1]
FTO global fee is calculated incorrectly for turnover of 1.5 million, when the turnover is 1.4 million it is correctly calculated. Above 1 million the fee is 3000 plus 350 for every million above that. Because of erroneous rounding 350 is added from 1.5 (and 2.5, etc,) instead 2 million.

**Comment by bbsen** [comment]
Still needs to be tested.

**Comment by bmango** [comment]
That's great. Thank you. Maybe we can get Anton to test...

**Comment by bmango** [comment]
Perhaps I can merge this and we can revisit it if there are any problems?

**Comment by bbsen** [comment]
It would be nice if we have some preview mechanism. I have created a test page, but that doesn't work from github yet due to security issues. I have placed it temporarily on some my site for Anton to review.
